kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ofridman-mrs-viewer # Need to find a proper name for the role binding
  namespace: rhoai-model-registries # Verify the namespace
subjects:
  - kind: ServiceAccount
    name: ofridman-sa
    namespace: ofridman-edb-recommender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-modelregistry-sample
